# Generated by Django 6.0.5 on 2026-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
